# Generated by Django 3.0.5 on 2020-05-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_remove_friend_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='last1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
