# Generated by Django 3.0.5 on 2020-05-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_friend_last1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='nick_name',
            new_name='email',
        ),
    ]
