# Generated by Django 3.0.5 on 2020-05-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200523_1811'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='likes',
            new_name='ph',
        ),
    ]
