# Generated by Django 3.0.5 on 2020-05-23 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_auto_20200523_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='last1',
            new_name='occ',
        ),
    ]
